server:
  port: 9091
  
spring:
  application:
    name: api-gateway          # 显示的Application名字

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
