server:
  port: 8001

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://112.74.89.58:42569/eureka

env: dev

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://212.64.11.85:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 212.64.11.85
    port: 6379
    
  rabbitmq:
    host: 212.64.11.85
    port: 5672                        # 是客户端的地址，不是浏览器管理端的                 #
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5         # 五个通道
        max-concurrency: 10     # 最大 10 个通道
        acknowledge-mode: manual       # 默认情况下消息消费者是自动 ack （确认）消息的，如果要手动 ack（确认）则需要修改确认模式为 manual
        prefetch: 1   #  需要并行1
  zipkin:
    base-url: http://212.64.11.85:9411/
  sleuth:
    sampler:
      probability: 1   # 抽样比例100%


    
girl:
  age: 27
  name: Louis
